name: .NET Core Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:  # This allows you to manually trigger the workflow

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]  # You can also add ubuntu-latest if needed
        dotnet-version: [8.0.x]  # Or whatever version you are using

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: List repository file structure
        run: dir Application/bin

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: 'Application/bin/Debug/net8.0'  # Adjust this path to point to your build output folder

      - name: Run tests
        run: dotnet test --configuration Release
